version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: destiny-limo-db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/db-scripts:/docker-entrypoint-initdb.d

  webapi:
    build:
      context: ./appServer/DestinyLimoServer
      dockerfile: Dockerfile
    ports:
      - "5293:5293"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db

  angular-app:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "9080:9080"

volumes:
  db_data:
