version: '3.8'

services:
  webapi:
    build:
      context: ./appServer/DestinyLimoServer
      dockerfile: Dockerfile
    ports:
      - "5293:5293"
    network_mode: "host"
    volumes:
      - /var/clients/webforless/destiny-limo/prod/uploads:/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  angular-app:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "9080:9080"